name: test

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - feature/release

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make test
